module.exports = [
    {
        id: 1, 
        title: "Raz Pizza", 
        instructions: "Preheat oven to 420F. Spread the dough onto pizza pan-Cut all the ingredients into cubes-Cook the dough for 10 mins-Remove from oven, add all toppings and cook for additional 15mins!", 
        user_id: 1, 
        likes: 10, 
        category: "Dinner", 
        photo: "http://localhost:5050/public/RazPizza.png", 
        updated_at: "2022-09-20 7:28"}, 
    {
        id: 2, 
        title: "Fish Tacos", 
        instructions: "Prepare fish batter by mixing milk, eggs and flour-Dip fish fillets into the batter and drop into hot oil-Meanwhile add salt, pepper and vinegar to red cabbage, let sit for 15mins-On a hot skillet add tortillas and toast them-Add a bit of everything and serve!", 
        user_id: 2, 
        likes: 20, 
        category: "Dinner", 
        photo: "http://localhost:5050/public/FishTacos.png", 
        updated_at: "2022-09-21 7:28"}, 
    {
        id: 3, 
        title: "Mini Frittatas", 
        instructions: "Cut up cooked bacon into small pieces, also cut all veggies into cubes-Beat eggs in a big bowl and add veggies, bacon, and eggs-pour mixture into muffin tins and top with some cheese-cook for 20 mins in preheated 350F oven!", 
        user_id: 3, 
        likes: 10, 
        category: "Breakfast", 
        photo: "http://localhost:5050/public/MiniFrittata.png", 
        updated_at: "2022-09-20 7:28"}, 
    {
        id: 4, 
        title: "Protein Pancake with Berries", 
        instructions: "Beat all ingredients together on low until protein powder is dissolved.-Spray skillet with non-stick coconut oil spray-Pour mix onto skillet to desired pancake size and fry on medium heat until thoroughly cooked.-You should end up with about 2 big pancakes, or 4 small pancakes. Amount varies slightly by desired size of pancake.", 
        user_id: 4, 
        likes: 5, 
        category: "Breakfast", 
        photo: "http://localhost:5050/public/PancakeBerries.png", 
        updated_at: "2022-09-22 7:28"}, 
    {
        id: 5, 
        title: "Tuna Salad Sandwich", 
        instructions: "Boil 2 medium potatoes for 20mins, cut into cubes once cooked-In a large bowl, mix a can of tuna with potatoes, cilantro, salt, pepper and mayo-Heat up a skillet with butter, add tuna mixture to two toast breads, and place into the skilled, cooked for 2 mins on each side!", 
        user_id: 5, 
        likes: 10, 
        category: "Lunch", 
        photo: "http://localhost:5050/public/TunaSalad.png", 
        updated_at: "2022-09-20 7:28"}, 
    {
        id: 6, 
        title: "Garlic Green Beans", 
        instructions: "Heat up some oil-Add the garlic, once soften and fragrant, add the remaining ingredients-Add splash of water, close the lid immediatley-Cook for 5 mins", 
        user_id: 1, 
        likes: 0, 
        category: "Lunch", 
        photo: "http://localhost:5050/public/GarlicGreenBeans.png", 
        updated_at: "2022-09-22 6:50"}, 
    {
        id: 7, 
        title: "Beef & Broccoli", 
        instructions: "Cover and freeze steak 20 minutes for easier slicing-Combine coconut aminos, 2 Tbsp. sesame oil, honey, garlic, ginger and black pepper in a bowl, stir well. Add flank steak and let marinade for 15 minutes-Place a large skillet over medium heat and add 1 Tbsp. sesame oil. Add broccoli florets and sauté 4 to 5 minutes, partially covered with lid, stirring or tossing several times until broccoli is bright green and crisp-tender then remove from pan. Tip: If you prefer softer broccoli, add 2 Tbsp. water before covering with the lid and it will steam cook the broccoli-Increase heat to high heat. Add steak in a single layer and sauté 2 minutes per side or just until cooked through. Quickly pull out a piece to test if fully cooked-Add the remaining marinade, reduce heat to medium/low and simmer 3 to 4 minutes. It will thicken. Add broccoli and stir to combine. Stir in 1 to 2 Tbsp. water to thin the sauce if desired. Add flank steak and enjoy!", 
        user_id: 2, 
        likes: 50, 
        category: "Dinner", 
        photo: "http://localhost:5050/public/BeefBroccoli.png", 
        updated_at: "2022-09-24 9:50"}, 
    {
        id: 8, 
        title: "Blackened Salmon Caesar Salad", 
        instructions: "Cut salmon to desired size, season with dry seasonings (Toss chicken in large bowl with buffalo sauce, lemon juice, ranch seasoning, and garlic powder. Transfer all to large baking pan and bake for 18 to 25 minutes-Heat oil in skillet until hot. Place salmon, skin side up and cook 2 to 3 minutes. Flip and cook additional 4 to 5 minutes-For Salad: Heat skillet over medium heat, add chopped bacon and cook through. Set aside.-Whisk together caesar dressing ingredients, set aside.-In a large bowl, combine shaved brussels sprouts, bacon, parmesan and caesar dressing. Toss to combine.-Serve and top with blackened salmon filets.-Salt and pepper to taste.", 
        user_id: 3, 
        likes: 10, 
        category: "Dinner", 
        photo: "http://localhost:5050/public/BlackendSalmon.png", 
        updated_at: "2022-09-23 9:50"}, 
    {
        id: 9, 
        title: "Tuna Poke Bowl", 
        instructions: "In a small pot, add 1 cup of jasmine rice with 2 cups of water. Bring to boil. When boiling, reduce heat to low and simmer until all water has cooked into rice.-In a medium bowl, combine tuna with scallions, garlic, ginger, gluten free soy sauce or coconut aminos and sesame oil. Toss to combine and set aside.-While tuna is marinating, cut your avocado and cucumber.-In two bowls, layer rice, tuna, carrots, cucumber, avocado and scallions.-Drizzle with optional toppings of mayonnaise, siracha and sesame seeds.", 
        user_id: 4, 
        likes: 20, 
        category: "Lunch", 
        photo: "http://localhost:5050/public/TunaPokeBowl.png", 
        updated_at: "2022-09-21 8:50"}, 
    {
        id: 10, 
        title: "Healthy Fried Rice", 
        instructions: "In a large non-stick wok or skillet, heat 1 1/2 tsp sesame oil and 1 1/2 tsp of the coconut oil over medium-high heat. Once hot, add chicken pieces, season lightly with salt and pepper and sauté until cooked through, about 5 to 6 minutes. Transfer chicken to a plate and set aside.-In separate, small skillet, add 1⁄2 tsp. coconut oil and scramble eggs. Remove from heat and set aside.-Return large skillet to medium-high heat, add remaining 1 1/2 tsp sesame oil and 1 tsp coconut oil. Add peas, carrots and onions and sauté 1 minute. Add garlic and sauté 1 minute longer. Return chicken and eggs to skillet along with rice and quinoa mix. Add in coconut aminos and season with salt and pepper to taste.", 
        user_id: 5, 
        likes: 5, 
        category: "Lunch", 
        photo: "http://localhost:5050/public/FriedRice.png", 
        updated_at: "2022-09-24 8:50"}, 
    {
        id: 11, 
        title: "Banana Protein Muffins", 
        instructions: "Preheat oven to 375°.-In a blender, combine bananas, milk, chia seeds, whey, vanilla, cinnamon and zucchini. Once blended, the mixture should be the consistency of cake batter.-Hand-mix the pecans and oats into the batter (do not blend).-Line muffin tin with muffin liners. Muffins come out very moist, so this step is important!-Pour batter into muffin tins until about 80% full. Sprinkle optional toppings over the top.-Bake for 12-15 minutes, until golden brown and enjoy!", 
        user_id: 1, 
        likes: 1, 
        category: "Dessert", 
        photo: "http://localhost:5050/public/BananaMuffin.png", 
        updated_at: "2022-09-24 8:50"}, 
    {
        id: 12, 
        title: "Pesto Salmon w/ Potatoes & Green Beans", 
        instructions: "Preheat oven to 400 degrees.-While oven is preheating, add potatoes to pot and fill with water until covered. Place on stove and bring to boil. Cook for 11 to 13 minutes. Drain and set aside.-Place the potatoes, green beans and salmon on a baking sheet. Drizzle the potatoes and green beans with 1 to 2 Tbsp. olive oil and evenly divide pesto between salmon filets.-Squeeze lemon over all ingredients and sprinkle with salt and pepper.-Bake for 17 to 19 minutes, until salmon flakes easily.", 
        user_id: 2, 
        category: "Lunch", 
        photo: "http://localhost:5050/public/PestoSalmon.png", 
        updated_at: "2022-09-24 8:50"}, 
    {
        id: 13, 
        title: "Khanfaroosh", 
        instructions: "mix all ingredients and leave for 30 mins.-heat oil in deep fryer or large heavy skillet-using a spoon, pour the dough in oil as small circles to be fried from both sides-place on tissue to absorb excess oil", 
        user_id: 3, 
        category: "Dessert", 
        photo: "http://localhost:5050/public/Khanfroosh.png", 
        updated_at: "2022-09-24 8:50"}, 
    {
        id: 14, 
        title: "Brinner Bowl", 
        instructions: "Microwave potato for 3 to 5 minutes first). In a medium frying pan, melt 1⁄2 Tbsp. and sauté potato until crispy. Remove and set aside.-Melt another 1⁄2 Tbsp. of coconut oil in the frying pan and add cherry tomatoes, peppers and spinach. Sauté about 3 to 5 minutes. Add potatoes back in and set on very low, just enough to keep the mixture warm.-In a small frying pan, melt the rest of the coconut oil and turn temperature to low. Cook the egg over easy gently crack egg and cook slowly until whites are firm and yolks are still runny. It may help to cover with a lid.-In a bowl, add veggie, then gently top with fried egg. Enjoy!", 
        user_id: 4, 
        category: "Breakfast", 
        photo: "http://localhost:5050/public/BrinnerBowl.png", 
        updated_at: "2022-09-24 8:50"}
    ]